# Generated by Django 4.2.8 on 2024-01-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_21007', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_unit',
            field=models.CharField(max_length=255),
        ),
    ]
