# Generated by Django 4.2.8 on 2024-01-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_21007', '0002_alter_product_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingpoint',
            name='gps_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sellingpoint',
            name='gps_long',
            field=models.FloatField(default=0.0),
        ),
    ]
