# Generated by Django 4.2.8 on 2024-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_21007', '0003_alter_sellingpoint_gps_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
