# Generated by Django 4.2.8 on 2024-01-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_21007', '0005_product_id_alter_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
